### ISSUE TITLE
can't find crypto

### ISSUE THREAD

**Issue by maddentist** [gjuchault/otpts#10] opened 2020-09-04 07:58 UTC
Hi,

I installed version 2.0.0 through npm, it doesn't build. It appears that there is a dependency problem involved:

ERROR in ./node_modules/otpts/build/hotp.js
Module not found: Error: Can't resolve 'crypto' in 'E:\Repos\demokratia\frontend\node_modules\otpts\build'

ERROR in ./node_modules/otpts/build/secret.js
Module not found: Error: Can't resolve 'crypto' in 'E:\Repos\demokratia\frontend\node_modules\otpts\build'

**Comment by gjuchault** [comment] 2020-09-04 11:38
Hello,

Which node version are you using? `crypto` is native in the nodejs ecosystem (https://nodejs.org/docs/latest/api/crypto.html)

Can you also start a fresh node REPL and try to require crypto?
```sh
$ node
> require('crypto')
{ … }
```

Thanks

**Comment by maddentist** [comment] 2020-09-04 11:42
> Hello,
> 
> Which node version are you using? `crypto` is native in the nodejs ecosystem (https://nodejs.org/docs/latest/api/crypto.html)
> 
> Can you also start a fresh node REPL and try to require crypto?
> 
> ```shell
> $ node
> > require('crypto')
> { … }
> ```
> 
> Thanks

Hi, thanks for your very quick answer !

I'm developping an Angulat app (I'm a bit of a beginner here) with:
Angular CLI: 10.0.8
Node: 12.18.3
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.2.0
@angular/cli                      10.0.8
@angular/material                 10.2.0
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0

**Comment by gjuchault** [comment] 2020-09-04 11:46
Hello again :)

This module isn't browser-compatible, as it uses the nodejs `crypto` module, which is unavailable in the browser. You might want to try to add an alias in your webpack config from `crypto` to `crypto-browserify` https://github.com/crypto-browserify/crypto-browserify but this won't be supported by this library (yet, it seems to be a decent solution: I'm only using a few methods from crypto and they are implemented in the browserify version)

**Comment by gjuchault** [comment] 2020-09-05 13:15
I'll be closing as not a bug

**Closed as completed by gjuchault** 2020-09-05 13:15 UTC
